function spec = defineUnitsMapping(fileName)
%DEFINEUNITSMAPPING  Data dictionary for the sample dataset data/Units_example.mat ("Unit").
%
%   Returns a spec consumed by data.DataManager. Each row of spec.vars maps a
%   PROJECT name to a SOURCE field in the raw struct, with a human-readable
%   definition and an arrangement rule ('collect'):
%
%       'auto'   (default) pick automatically:
%                  scalar per unit      -> Nx1 column vector
%                  equal 1xk row vector -> Nxk matrix
%                  matrix / ragged      -> Nx1 cell
%       'rows'   force vertical stack of scalars/row-vectors  -> Nxk
%       'cell'   force one cell per unit                       -> Nx1 cell
%       'stack'  cat equal-size arrays on a new last dim       -> [size x N]
%       'string' char/string per unit -> Nx1 string (trimmed)
%
%   TO CUSTOMISE:
%     * Rename a project variable: change the 1st argument of v(...).
%       (By default project name == source field name.)
%     * Fix/extend a definition:   edit the 3rd argument.
%     * Items marked "VERIFY" are inferred from field names + the PV /
%       orientation-tuning context -- confirm against your analysis code.
%
%   Convention used in the names below:
%       L / NL  = Laser / No-Laser        P / NP = Preferred / Non-Preferred ori
%
%   See also: data.DataManager

    here     = fileparts(mfilename('fullpath'));      % ...<repo>/+data
    repoRoot = fileparts(here);                       % ...<repo>
    if nargin < 1 || isempty(fileName), fileName = 'Units_example.mat'; end   % default file

    spec.dataset   = 'Units';
    spec.sourceVar = 'Unit';                 % variable name *inside* the .mat
    %  Lives in the repository's data/ folder; FILE overrides only the name (the
    %  folder is fixed here). Registered as the 'example' dataset in
    %  data.defineDatasets. Drop another .mat with the same Unit structure into
    %  data/ and pass its name to load it instead -- see loadData's 'SourceFile'.
    spec.file      = fullfile(repoRoot, 'data', char(fileName));

    %  The shipped sample carries no recording-filename fields (Name, Name2,
    %  FName, FN): the app never reads them, and a recording is identified
    %  numerically by Dataset (DS) + Penetration (P). If your own file has
    %  them and you want them, add rows for them here.
    %
    %        project        source        description                                                    options
    spec.vars = [ ...
        v('id',          'id',          'Unit id within its recording.'); ...
        v('ch',          'ch',          'Recording channel / electrode number.'); ...
        v('Fr',          'Fr',          'Mean firing rate, [L NL] (Hz). VERIFY column order.',                          'units','Hz'); ...
        vsplit('Fr_NL',  'Fr', 2,       'Mean firing rate, no-laser (Hz).',                                       'units','Hz'); ...
        vsplit('Fr_L',   'Fr', 1,       'Mean firing rate, laser (Hz).',                                          'units','Hz'); ...
        v('Rsq',         'Rsq',         'Tuning-curve fit R^2, [L NL]. VERIFY.'); ...
        vsplit('Rsq_L',  'Rsq', 1,      'Tuning-curve fit R^2, laser (precomputed in file).'); ...
        vsplit('Rsq_NL', 'Rsq', 2,      'Tuning-curve fit R^2, no-laser (precomputed in file).'); ...
        v('Si',          'Si',          'Selectivity index, [L NL]. VERIFY.'); ...
        v('Cv',          'Cv',          'Circular variance of tuning, [L NL]. VERIFY.'); ...
        v('HBW',         'HBW',         'Tuning half-bandwidth, [L NL] (deg). VERIFY.',                         'units','deg'); ...
        v('F1F0',        'F1F0',        'F1/F0 modulation ratio, [L NL]. VERIFY.'); ...
        vsplit('F1F0_L', 'F1F0', 1,     'F1/F0 modulation ratio, laser (precomputed in file).'); ...
        vsplit('F1F0_NL','F1F0', 2,     'F1/F0 modulation ratio, no-laser (precomputed in file).'); ...
        v('Fr_L123',     'Fr_L123',     'Firing rate across 3 laser epochs/levels. VERIFY.',                   'units','Hz'); ...
        v('Fr_NL123',    'Fr_NL123',    'Firing rate across 3 no-laser epochs/levels. VERIFY.',               'units','Hz'); ...
        v('OPL',         'OPL',         'Count metric, Pref-ori Laser, 2 cols. VERIFY meaning.'); ...
        v('OPNL',        'OPNL',        'Count metric, Pref-ori No-Laser. VERIFY.'); ...
        v('ONPL',        'ONPL',        'Count metric, NonPref-ori Laser. VERIFY.'); ...
        v('ONPNL',       'ONPNL',       'Count metric, NonPref-ori No-Laser. VERIFY.'); ...
        v('FrPL',        'FrPL',        'Firing rate, Pref-ori Laser (Hz), 2 cols. VERIFY.',                  'units','Hz'); ...
        v('FrPNL',       'FrPNL',       'Firing rate, Pref-ori No-Laser (Hz). VERIFY.',                      'units','Hz'); ...
        v('FrNPL',       'FrNPL',       'Firing rate, NonPref-ori Laser (Hz). VERIFY.',                      'units','Hz'); ...
        v('FrNPNL',      'FrNPNL',      'Firing rate, NonPref-ori No-Laser (Hz). VERIFY.',                   'units','Hz'); ...
        v('LPow',        'LPow',        'Laser power level (a.u.).'); ...
        v('fit',         'fit',         'Fitted orientation tuning curve, 0-359 deg x [L NL]; stacked to 360x2xN.', 'collect','stack', 'units','deg'); ...
        vsplit('fit_NL', 'fit', 2,       'Fitted tuning curve, no-laser (0-359 deg); 360xN.',                  'collect','stack', 'units','deg'); ...
        vsplit('fit_L',  'fit', 1,       'Fitted tuning curve, laser (0-359 deg); 360xN.',                   'collect','stack', 'units','deg'); ...
        v('RasL',        'RasL',        'Spike raster, laser trials (trials x 2500 time bins); one cell per unit.'); ...
        v('RasNL',       'RasNL',       'Spike raster, no-laser trials (trials x 2500 time bins); one cell per unit.'); ...
        v('Ra',          'Ra',          'Response metric Ra (scalar). VERIFY.'); ...
        v('Rb',          'Rb',          'Response metric Rb (scalar). VERIFY.'); ...
        v('Rbn',         'Rbn',         'Response metric Rbn (scalar). VERIFY.'); ...
        v('Dataset',     'DS',          'Dataset'); ...
        v('Penetration', 'P',           'Penetration index.'); ...
        v('U_unity',     'UU',          'Unit Unity number'); ...
        v('Ori_N',       'Ori_N',       'Number of '); ...
        v('Rast_time',   'Raster_Start_Duration_End_time', 'Raster Start Duration End time'); ...
        v('EI',          'EI',          'Excitation or Inhibition Experiment?.', 'collect','string'); ...
        v('LG',          'LG',          'recording layer group SG_G_IG_Deep', 'collect','string'); ...
    ];
end

% ----------------------------------------------------------------------- %
function d = v(name, source, desc, varargin)
%V  Build one source-variable definition (with optional name/value extras).
    d.name        = name;
    d.kind        = 'source';
    d.source      = source;
    d.description = desc;
    d.units       = '';
    d.collect     = 'auto';
    d.transform   = [];
    d.dependsOn   = {};
    d.compute     = [];
    for i = 1:2:numel(varargin)
        d.(varargin{i}) = varargin{i+1};
    end
end

% ----------------------------------------------------------------------- %
function d = vsplit(name, source, col, desc, varargin)
%VSPLIT  One project variable = one column (slice) of a per-unit field.
%   Builds a single source definition (like v) whose transform picks column
%   COL of each unit's SOURCE value:
%       1xk row per unit    -> x(:,col) is a scalar   -> Nx1
%       mxk matrix per unit -> x(:,col) is an mx1 col  -> add 'collect','stack'
%                                                          to get mxN (singleton
%                                                          dims are squeezed out)
%   Argument order mirrors v(): project NAME first, then SOURCE. Any extra
%   name/value pairs (e.g. 'units','Hz', 'collect','stack') pass through to v.
%
%   Examples:
%       vsplit('Fr_L',  'Fr',  2, 'Mean firing rate, laser (Hz).', 'units','Hz')
%       vsplit('fit_L', 'fit', 2, 'Tuning fit, laser (0-359 deg).', ...
%              'collect','stack', 'units','deg')
    d = v(name, source, desc, 'transform', @(x) x(:,col), varargin{:});
end
